


development:
  adapter: postgresql
  encoding: unicode
  database: letterbox_dev
  pool: 5
  username: ysbecca
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: letterbox_test
  pool: 5
  username: ysbecca
  password: